./tb/tb_sigma_gen.sv
./vmod/flexdpe.v
./vmod/xbar.v
./vmod/benes.v
./vmod/mult_gen.v 
./vmod/mult_switch.v
./vmod/bfp16_mult.v 
./vmod/adder_switch.v 
./vmod/edge_adder_switch.v
./vmod/bfp32_adder.v
./vmod/reduction_mux.v
./vmod/fan_network.v 
./vmod/fan_ctrl.v
